@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.chiveq.golemartifice.content;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;